### ISSUE TITLE
v5.77 Adventure Mode Build System Blank Screen

### ISSUE THREAD

**Issue by backlands** [mifki/df-twbt#55] opened 2017-03-17 14:57 UTC
When playing Adventure Modeand entering the Build `b` menu while using TWBT the screen goes blank except for the side bar menu. This makes it impossible to build structures while using TWBT.

This issue can be replicated by downloading PeridexisErrant Lazy Newb Pack and starting the game in Adventure Mode and using the Build `b` menu.

**Comment by lethosor** [comment] 2017-03-17 15:43
Part of the issue is that DFHack (up to 0.43.05-beta1) didn't have the enum value for that menu listed. That's been fixed in https://github.com/DFHack/df-structures/commit/e1aa827e02bc8083553a26fd8ec04b4f023af409. 

[This function](https://github.com/mifki/df-twbt/blob/b321c0ed22e82e516c429d059d073f9e79398667/twbt.cpp#L365) will also have to be updated by adding a check for `df::ui_advmode_menu::Build` in order for TwbT to work in that menu (and it really shouldn't be using magic numbers for some of those other menus anyway)

**Comment by pronvit** [comment] 2017-03-21 03:25
@lethosor There's a comment https://github.com/mifki/df-twbt/blob/b321c0ed22e82e516c429d059d073f9e79398667/twbt.cpp#L367
But yeah it's time to update it now that all the values exist and correct in dfhack.

**Comment by lethosor** [comment] 2017-03-21 03:38
I think that I've verified those values since then.

**Comment by pronvit** [comment] 2017-03-23 10:09
Should be fixed in v5.78

**Closed by pronvit** 2017-03-23 10:09 UTC
